LSTM:
  units: 100

Dense:
  units: 221
  activation: "softmax"

Embedding:
  input_dim: 221
  output_dim: 100
  input_length: 39

to_categorical:
  num_classes: 221

compile:
  loss: "categorical_crossentropy"
  optimizer: "adam"
  metrics: "['accuracy']"

fit:
  epoch: 100