Dense:
  activation: softmax
  units_dense: 221
Embedding:
  input_dim: 221
  input_length: 39
  output_dim: 100
LSTM:
  units_lstm: 100
compile:
  loss: categorical_crossentropy
  metrics:
  - accuracy
  optimizer: adam
fit:
  epoch: 100
pad_sequences:
  padding: pre
to_categorical:
  num_classes: 221
