pad_sequences:
  padding: "pre"

to_categorical:
  num_classes: 221

LSTM:
  units: 100

Dense:
  units: 221
  activation: "softmax"

Embedding:
  input_dim: 221
  output_dim: 100
  input_length: 39

compile:
  loss: "categorical_crossentropy"
  optimizer: "adam"
  metrics: "['accuracy']"

fit:
  epoch: 100