artifacts_root: artifacts
data_ingestion:
  destination_folder: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.txt
  root_dir: artifacts/data_ingestion
data_transformation:
  Data_path: artifacts/data_ingestion\NWPxyz.txt
  root_dir: artifacts/data_transformation
  tokenizer_name: token.joblib
data_validation:
  Data_path: artifacts/data_ingestion\NWPxyz.txt
  STATUS_FILE: artifacts/data_validation/status.txt
  root_dir: artifacts/data_validation
model_evaluation:
  array_path: artifacts/data_transformation/arrays.npz
  metric_file_name: artifacts/model_evaluation/metrcis.json
  model_path: artifacts/model_trainer/model.joblib
  root_dir: artifacts/model_evaluation
model_trainer:
  array_path: artifacts/data_transformation/arrays.npz
  model_name: model.joblib
  root_dir: artifacts/model_trainer
