artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.txt
  destination_folder: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  Data_path: artifacts/data_ingestion/NWP.txt
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  Data_path: artifacts/data_ingestion/NWP.txt